### ISSUE TITLE
Uncaught (in promise) ReferenceError: require is not defined     at resolve (app.js:25:13)     at h2 (createInertiaApp.js:8:52)     at exports.createInertiaApp (createInertiaApp.js:12:24)

### ISSUE THREAD

**Issue by ah-rasel** [YaroslavFedan/modules-inertia#2]
**Thank you for this package, Can you please help me with this? i am new to inertia & vue3**

I have followed all the steps from above 

**I am getting this error** 
> Uncaught (in promise) ReferenceError: require is not defined
>     at resolve (app.js:25:13)
>     at h2 (createInertiaApp.js:8:52)
>     at exports.createInertiaApp (createInertiaApp.js:12:24)
>     at app.js:12:1
> resolve @ app.js:25
> h2 @ createInertiaApp.js:8
> exports.createInertiaApp @ createInertiaApp.js:12
> (anonymous) @ app.js:12

### Here is my app.js file in ### main app (Not in any module )

```
`import './bootstrap';
import '../css/app.css';

import { createApp, h } from 'vue';
import { createInertiaApp } from '@inertiajs/inertia-vue3';
import { InertiaProgress } from '@inertiajs/progress';
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
import { ZiggyVue } from '../../vendor/tightenco/ziggy/dist/vue.m';

const appName = window.document.getElementsByTagName('title')[0]?.innerText || 'Laravel';

createInertiaApp({
    resolve: (name) => {
        let page = null;

        let isModule = name.split("::");
        if (isModule.length > 1) {
            let module = isModule[0];
            let pathTo = isModule[1];
            // @modules is an alias of the module folder or just specify the path 
            // from the root directory to the folder modules             
            // for example ../../modules
            page = require(`@modules/${moduleName}/${pathToFile}.vue`);
        } else {
            page = require(`./Pages/${name}`);
        }
        //...
        return page.default;
    },
    setup({ el, App, props, plugin }) {
        createApp({ render: () => h(App, props) })
            .use(plugin)
            .mount(el);
    },
});

InertiaProgress.init({ color: '#4B5563' });
`

**Comment by YaroslavFedan** [comment]
This package is based on webpack.mix.js.
You use according to code
`import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';`
vite build tool
When vite is used, the require method cannot be used. Only import
For example:
`import.meta.glob("some_file.vue")`

At this point, I can offer a transitional solution (which has not yet been tested for a modular structure), I will solve it in the near future.

But you can try to do it yourself based on the script that was written for webpack.mix
and using this:

in vite.config.js

```
export default defineConfig({
 // ....
  resolve: {
    alias: {
      "@modules": path.resolve(__dirname + "/modules"),
    },
    extensions: [".js", ".vue"],
  },
});

```
in main js file


```
createInertiaApp({
  resolve: (name) => {
   
    let page = null;
    let isModule = name.split("::");

    if (isModule.length > 1) {
            let module = isModule[0];
            let pathTo = isModule[1];
           page = resolvePageComponent(
             `@modules/${moduleName}/${pathToFile}.vue`,
              import.meta.glob(`@modules/${moduleName}/${pathToFile}.vue`)
            );
      } else {
         page = resolvePageComponent(
            `./Pages/${name}.vue`,
            import.meta.glob("./Pages/**/*.vue")
          );
      }

    return page;
  },
  setup({ el, app, props, plugin }) {
    Vue.use(plugin);
    Vue.use(ZiggyVue, Ziggy);
   

    const App = new Vue({ render: (h) => h(app, props) });
    return App.$mount(el);
  },
});
```

**Comment by mariusberget92** [comment]
Just wanted to share my code if anyone else comes across the same problem. Created my own function for resolving the component name.

```
function resolvePageComponent(name) {
  // Check if the name is a module 
  let isModule = name.split('::')

  if (isModule.length > 1) {

    // Import pages from the modules folder
    let pages = import.meta.glob('../../../modules/**/Pages/**/*.vue')

    // Sort and replace the wrong slash and dot with the correct slash
    const path = Object.keys(pages)
      .sort((a, b) => a.length - b.length)
      .find(path =>
        path.endsWith(
          `${isModule[1]
            .replaceAll('\\', '/')
            .replaceAll('.', '/')}.vue`,
        ),
      )
    
    // Throw an error if the page is not found
    if (!path) {
      throw new Error(`Page not found: ${isModule[1]}`)
    }

    // Return the page
    return typeof pages[path] === 'function' ? pages[path]() : pages[path]

  } 
  
  else {

    // Import pages from the core application folder since it's not a module
    let pages = import.meta.glob('./Pages/**/*.vue')

    // Sort and replace the dot with the correct slash
    const path = Object.keys(pages)
      .sort((a, b) => a.length - b.length)
      .find(path => path.endsWith(`${name.replaceAll('.', '/')}.vue`))

    // Throw an error if the page is not found
    if (!path) {
      throw new Error(`Page not found: ${name}`)
    }

    // Return the page
    return typeof pages[path] === 'function' ? pages[path]() : pages[path]
  }
}
```

Then when creating the app instance:
```
createInertiaApp({
  ...
  resolve: name => resolvePageComponent(name),
  ...
})
```

**Comment by YaroslavFedan** [comment]
Thanks, great idea. Need to try and add )

вс, 4 дек. 2022 г. в 17:44, Marius Berget ***@***.***>:

**Comment by alwinaugustin** [comment]
> function resolvePageComponent(name) {
>   // Check if the name is a module 
>   let isModule = name.split('::')
> 
>   if (isModule.length > 1) {
> 
>     // Import pages from the modules folder
>     let pages = import.meta.glob('../../../modules/**/Pages/**/*.vue')
> 
>     // Sort and replace the wrong slash and dot with the correct slash
>     const path = Object.keys(pages)
>       .sort((a, b) => a.length - b.length)
>       .find(path =>
>         path.endsWith(
>           `${isModule[1]
>             .replaceAll('\\', '/')
>             .replaceAll('.', '/')}.vue`,
>         ),
>       )
>     
>     // Throw an error if the page is not found
>     if (!path) {
>       throw new Error(`Page not found: ${isModule[1]}`)
>     }
> 
>     // Return the page
>     return typeof pages[path] === 'function' ? pages[path]() : pages[path]
> 
>   } 
>   
>   else {
> 
>     // Import pages from the core application folder since it's not a module
>     let pages = import.meta.glob('./Pages/**/*.vue')
> 
>     // Sort and replace the dot with the correct slash
>     const path = Object.keys(pages)
>       .sort((a, b) => a.length - b.length)
>       .find(path => path.endsWith(`${name.replaceAll('.', '/')}.vue`))
> 
>     // Throw an error if the page is not found
>     if (!path) {
>       throw new Error(`Page not found: ${name}`)
>     }
> 
>     // Return the page
>     return typeof pages[path] === 'function' ? pages[path]() : pages[path]
>   }
> }

Where you have added this function ? In a separate file or the same `app.js` ?

**Comment by mariusberget92** [comment]
> > function resolvePageComponent(name) {
> > // Check if the name is a module
> > let isModule = name.split('::')
> > if (isModule.length > 1) {
> > ```
> > // Import pages from the modules folder
> > let pages = import.meta.glob('../../../modules/**/Pages/**/*.vue')
> > 
> > // Sort and replace the wrong slash and dot with the correct slash
> > const path = Object.keys(pages)
> >   .sort((a, b) => a.length - b.length)
> >   .find(path =>
> >     path.endsWith(
> >       `${isModule[1]
> >         .replaceAll('\\', '/')
> >         .replaceAll('.', '/')}.vue`,
> >     ),
> >   )
> > 
> > // Throw an error if the page is not found
> > if (!path) {
> >   throw new Error(`Page not found: ${isModule[1]}`)
> > }
> > 
> > // Return the page
> > return typeof pages[path] === 'function' ? pages[path]() : pages[path]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > else {
> > ```
> > // Import pages from the core application folder since it's not a module
> > let pages = import.meta.glob('./Pages/**/*.vue')
> > 
> > // Sort and replace the dot with the correct slash
> > const path = Object.keys(pages)
> >   .sort((a, b) => a.length - b.length)
> >   .find(path => path.endsWith(`${name.replaceAll('.', '/')}.vue`))
> > 
> > // Throw an error if the page is not found
> > if (!path) {
> >   throw new Error(`Page not found: ${name}`)
> > }
> > 
> > // Return the page
> > return typeof pages[path] === 'function' ? pages[path]() : pages[path]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > }
> 
> Where you have added this function ? In a separate file or the same `app.js` ?

Same as `app.js`. But I got multiple root views, so also in `dashboard.js` and `auth.js`.
